# Generated by Django 3.0.9 on 2020-08-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_auto_20200830_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('roles', models.ManyToManyField(to='course_app.RoleModel')),
            ],
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='expert_skills',
            field=models.ManyToManyField(related_name='expert_skills', to='course_app.SkillModel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='intermediate_skills',
            field=models.ManyToManyField(related_name='intermediate_skills', to='course_app.SkillModel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='novice_skills',
            field=models.ManyToManyField(related_name='novice_skills', to='course_app.SkillModel'),
        ),
    ]
