# Generated by Django 3.0.9 on 2020-08-31 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0012_auto_20200830_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='expert_skills',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='intermediate_skills',
        ),
    ]
