# Generated by Django 3.0.9 on 2020-08-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0013_auto_20200831_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='expert_skills',
            field=models.ManyToManyField(blank=True, related_name='expert_skills', to='course_app.SkillModel'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='intermediate_skills',
            field=models.ManyToManyField(blank=True, related_name='intermediate_skills', to='course_app.SkillModel'),
        ),
    ]
